# Generated by Django 4.0.1 on 2022-01-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stablishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('size', models.PositiveIntegerField(default=0)),
                ('state', models.IntegerField(choices=[[0, 'Open'], [1, 'Close']])),
                ('country', models.CharField(max_length=50)),
                ('category', models.IntegerField(choices=[[0, 'Restaurant'], [1, 'Coffee Shop'], [2, 'Bar']])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stablishments.city')),
            ],
        ),
        migrations.RenameModel(
            old_name='UserTeilur',
            new_name='UserHoisu',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordertoken',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='token',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderToken',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
